# Generated by Django 4.1.3 on 2024-03-12 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuto',
            old_name='name',
            new_name='product',
        ),
    ]
