# Generated by Django 4.1.3 on 2024-03-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_rename_name_tuto_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuto',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tuto',
            name='product',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
